redhat-plumbers/systemd-rhel9

tmpfiles.d/etc.conf.in
=> (#1989472) tmpfiles: don't create resolv.conf -> stub-resolver symlink

src/login/pam_systemd.c
Already merged upstream: https://github.com/systemd/systemd/pull/19965/
=> Check return value of pam_get_item/pam_get_data functions (#1973210)

src/basic/random-util.h
=> (#1982603) random-util: increase random seed size to 1024

man/udev.xml, src/udev/udev-rules.c, test/rule-syntax-check.py
This reverts commit f2b8052fb648b788936dd3e85be6a9aca90fbb2f.
RHEL-only
Resolves: #1982666
=> Revert "udev: remove WAIT_FOR key"

man/systemctl.xml
=> (#1982596) man: mention System Administrator's Guide in systemctl manpage

.github/workflows/build_test.sh, src/core/load-fragment.c, src/core/unit.c
=> (#2013213) core: decrease log level of messages about use of KillMode=none

src/shutdown/umount.c
Current md_list_get() implementation filters all block devices, started from
"md*". This is ambiguous because list could contain:
- partitions created upon md device (mdXpY)
- external metadata container- specific type of md array.
For partitions there is no issue, because they aren't handle STOP_ARRAY
ioctl sent later. It generates misleading errors only.
Second case is more problematic because containers are not locked in kernel.
They are stopped even if container member array is active. For that reason
reboot or shutdown flow could be blocked because metadata manager cannot be
restarted after switch root on shutdown.
Add filters to remove partitions and containers from md_list. Partitions
can be excluded by DEVTYPE. Containers are determined by MD_LEVEL
property, we are excluding all …
=> (#2047682) shutdown: get only active md arrays.

.mergify.yml
RHEL-only
Related: #2087652
---
This change has been made by @jamacku from https://mergify.com config editor.
=> (#2087652) ci(Mergify): Add `ci-waived` logic

src/journal/test-journal-interleaving.c, src/libsystemd/sd-bus/sd-bus.c, src/libsystemd/sd-journal/sd-journal.c, src/shared/dissect-image.c, src/shared/dissect-image.h, src/systemctl/systemctl-show.c, test/units/testsuite-13.sh, test/units/testsuite-21.sh, test/units/testsuite-45.sh
A couple of patches for regressions which are going to be part of the next stable releases (including v252.2) + a couple of rhel-only patches for tests.
=> (#2138081) A couple of post v252.1 backports

src/basic/io-util.c, src/home/homework-luks.c, src/libsystemd/sd-bus/bus-socket.c, src/libsystemd/sd-bus/sd-bus.c, src/libsystemd/sd-netlink/sd-netlink.c, src/resolve/resolved-manager.c, src/shared/ask-password-api.c, src/shared/barrier.c, src/shared/utmp-wtmp.c, src/shared/varlink.c, src/stdio-bridge/stdio-bridge.c
Resolves: [#2137584](https://bugzilla.redhat.com/show_bug.cgi?id=2137584)
=> (#2137584) ppoll() + EINTR fixes

src/basic/io-util.h, src/coredump/coredump.c
Resolves: [#2155517](https://bugzilla.redhat.com/show_bug.cgi?id=2155517)
=> (#2155517) Do not allow user to access coredumps with changed uid/gid/capabilities

man/systemd-sleep.conf.xml, src/shared/sleep-config.c, src/shared/sleep-config.h, src/sleep/sleep.c, src/sleep/sleep.conf
Resolves: [#2151612](https://bugzilla.redhat.com/show_bug.cgi?id=2151612)
=> (#2151612) Restore pre-252 behavior of HibernateDelaySec=

test/units/testsuite-64.sh
Original issue: https://bugzilla.redhat.com/show_bug.cgi?id=1985288
(cherry picked from commit 6299b6e5e6df32516fcaba9a93d966bad9043748)
Related: #1985288
---
I heard there will be at least one another build for 9.2, so let's get this one in to further improve our coverage.
=> (#1985288) test: add coverage for #24177

src/libsystemd/sd-journal/journal-file.c
(cherry picked from commit 0399902440fbaea5b163254f70be57dbedb7131e)
Resolves: #2173682
=> (#2173682) journal-file: Fix return value in bump_entry_array()

man/systemd-system-update-generator.xml, man/systemd.offline-updates.xml, man/systemd.special.xml, src/system-update-generator/system-update-generator.c, units/system-update-cleanup.service
(cherry picked from commit b9dac418372401742609bd600f05267ae3a724de)
Resolves: [#2203133](https://bugzilla.redhat.com/show_bug.cgi?id=2203133)
=> (#2203133) Support /etc/system-update for OSTree systems

.github/advanced-commit-linter.yml, .github/workflows/gather-metadata.yml, .github/workflows/source-git-automation.yml, docs/ENVIRONMENT.md, src/basic/compress.c, src/basic/compress.h, src/journal/journald-server.c, src/libsystemd/sd-journal/journal-def.h, src/libsystemd/sd-journal/journal-file.c, src/libsystemd/sd-journal/journal-file.h, test/units/testsuite-04.sh
=> (#2184929) sd-journal: allow to specify compression algorithm through env

src/core/transaction.c, src/coredump/coredump.c, src/pstore/pstore.c, test/TEST-06-SELINUX/test.sh, test/testsuite-06.units/load-systemd-test-module.service, test/units/testsuite-04.sh, test/units/testsuite-74.pstore.sh
Also closes #154, except for the serialization stuff, since I'm not sure how much we want it in RHEL, as there was quite a number of follow-ups.
=> (#2170883) Backport systemd-pstore fixes & tests

src/shared/elf-util.c
=> (#2222259) Discard PT_LOAD segment early based on the start address

src/core/dbus-mount.c
When What= or Options= may contain invalid UTF8 chars.
Replaces aaf7b0e41105d7b7cf30912cdac32820f011a219 (#27541).
(cherry picked from commit 4804da58536ab7ad46178a03f4d2da49fd8e4ba2)
Resolves: #2208240
=> (#2208240) core/mount: escape invalid UTF8 char in dbus reply

rules.d/60-persistent-storage.rules, test/units/testsuite-64.sh
=> (#2172509) NVMe by-id symlink fixes

src/login/loginctl.c, test/units/testsuite-35.sh
Resolves: [#2209912](https://bugzilla.redhat.com/show_bug.cgi?id=2209912)
=> (#2209912) Add idle time column to loginctl list-sessions

src/resolve/resolvectl.c, src/resolve/resolved-bus.c
=> (#2161260) display localhost as Global DNS server

.github/advanced-commit-linter.yml, .github/tracker-validator.yml, .github/workflows/source-git-automation-on-demand.yml, .github/workflows/source-git-automation.yml
* on schedule and on demand workflows
* Added Tracker validation for Bugzilla and Jira
rhel-only
Resolves: RHEL-1086
=> (RHEL-1086) ci: Extend source-git-automation

.github/pull-request-validator.yml, .github/workflows/source-git-automation-on-demand.yml, .github/workflows/source-git-automation.yml
=> (RHEL-1086) ci: enable source-git automation to validate reviews and ci results

.github/auto-merge.yml, .github/workflows/source-git-automation-on-demand.yml, .github/workflows/source-git-automation.yml
=> (RHEL-1086) ci: enable auto-merge GH Action

.github/workflows/source-git-automation-on-demand.yml, .github/workflows/source-git-automation.yml
=> (RHEL-1086) ci: `permissions: write-all`

src/kernel-install/meson.build
(cherry picked from commit 4c181c1a33ef4de0130a131a2b332348dda672ed)
Resolves: RHEL-16354
=> (RHEL-16354) meson: Properly install 90-uki-copy.install

.github/workflows/deploy-man-pages.yml
=> (RHEL-1086) ci: deploy systemd man to GitHub Pages

.github/tracker-validator.yml
=> (RHEL-30372) ci(src-git): update list of supported products

src/core/system.conf.in, src/coredump/coredump.conf, tmpfiles.d/systemd.conf.in
=> (RHEL-15501) Change default coredump policy

.github/workflows/deploy-man-pages.yml
=> (RHEL-30372) ci: update manpage deployment workflow

man/org.freedesktop.systemd1.xml, man/systemd-analyze.xml, src/basic/ratelimit.c, src/basic/ratelimit.h, src/core/dbus-manager.c, src/core/dbus.c, src/core/dbus.h, src/core/manager-serialize.c, src/core/manager.c, src/core/manager.h, src/core/org.freedesktop.systemd1.policy.in, test/test-functions, test/units/testsuite-65.sh
=> (RHEL-35703) manager: restrict Dump*() to privileged callers or ratelimit

.github/advanced-commit-linter.yml, CONTRIBUTING.md
rhel-only: ci
Related: RHEL-30372
=> (RHEL-30372) ci: add support for rhel-only parameters

man/tmpfiles.d.xml
Reported and diagnosed by gitterman. Fixes #26617.
(cherry picked from commit f90360eb7417e083650034ad819790df0c389bd1)
Resolves: RHEL-74015
=> (RHEL-74015) man/tmpfiles: fix off-by-one in example

src/basic/macro.h, src/libsystemd/sd-event/sd-event.c, src/libsystemd/sd-event/test-event.c, src/shared/tests.h
=> (RHEL-103753)  Drop inotify event from buffer when no event source is triggered

src/core/dbus.c, src/core/dbus.h, src/core/manager-serialize.c, src/core/manager.c, src/core/manager.h, src/core/service.c, src/core/unit.c, src/core/unit.h, src/libsystemd/sd-bus/bus-control.c, src/libsystemd/sd-bus/bus-control.h, src/libsystemd/sd-bus/bus-internal.h, src/libsystemd/sd-bus/bus-track.c, src/libsystemd/sd-bus/sd-bus.c, src/shared/bus-util.c, src/shared/bus-util.h
=> (RHEL-31756) Fix for "Unexpected error response from GetNameOwner(): Connection terminated"

man/systemctl.xml, src/systemctl/systemctl-compat-halt.c, src/systemctl/systemctl-logind.c, src/systemctl/systemctl-logind.h, src/systemctl/systemctl-start-special.c, src/systemctl/systemctl.c, src/test/test-time-util.c
=> (RHEL-109488) Add --when for scheduled poweroff/halt/reboot/kexec support

src/basic/errno-util.h, src/basic/fd-util.c, src/shared/bus-util.c, src/shared/devnode-acl.c, src/shared/nscd-flush.c, src/test/test-errno-util.c
=> (RHEL-108598) fd-util: don't eat up errors in fd_cloexec_many 

man/systemctl.xml, src/systemctl/systemctl-compat-halt.c, src/systemctl/systemctl-logind.c, src/systemctl/systemctl-logind.h, src/systemctl/systemctl-start-special.c, src/systemctl/systemctl.c, src/test/test-time-util.c
=> (RHEL-110954) Add --when for scheduled poweroff/halt/reboot/kexec support

src/core/dbus.c, src/core/dbus.h, src/core/manager-serialize.c, src/core/manager.c, src/core/manager.h, src/core/service.c, src/core/unit.c, src/core/unit.h, src/libsystemd/sd-bus/bus-control.c, src/libsystemd/sd-bus/bus-control.h, src/libsystemd/sd-bus/bus-internal.h, src/libsystemd/sd-bus/bus-track.c, src/libsystemd/sd-bus/sd-bus.c, src/shared/bus-util.c, src/shared/bus-util.h, test/units/testsuite-64.sh
=> (RHEL-111628) Fix for "Unexpected error response from GetNameOwner(): Connection terminated"
