redhat-plumbers/systemd-rhel9

- man/logind.conf.xml
- src/login/logind-core.c
- src/login/logind.conf.in
RHEL-only
Resolves: #1959836
(cherry picked from commit 0b3833d6c3b751c6dfb40eeb2ef852984c58f546)
> (#1959836) logind: set RemoveIPC to false by default

- src/rfkill/rfkill.c
Backport of the "correct" fix from upstream, since the fix from #6 wasn't complete and the build kept failing with:
```
In file included from ../src/basic/macro.h:491,
from ../src/basic/alloc-util.h:9,
from ../src/rfkill/rfkill.c:13:
../src/rfkill/rfkill.c: In function ‘run’:
../src/rfkill/rfkill.c:339:70: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘int’ [-Werror=format=]
return log_error_errno(SYNTHETIC_ERRNO(EIO), "Short read of struct rfkill_event: (%zd < %lu)",
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/basic/log.h:195:86: note: in definition of macro ‘log_full_errno’
? log_internal(_level, _e, PROJECT_FILE, __LINE__, __func__, __VA_ARGS__) \
^~~~~~~~~~~
../src/rfkill/rfkill.c:339:32: note: in expansion of macro …
```
> (#1931710) rfkill: add some casts to silence -Werror=sign-compare

- man/systemd.exec.xml
- src/core/load-fragment.c
This allows "LoadCredentials=foo" to be used as shortcut for
"LoadCredentials=foo:foo", i.e. it's a very short way to inherit a
credential under its original name from the service manager into a
service.
(cherry picked from commit 8a29862e32fc7981fe16fc8dd79ad6863a8dc486)
Resolves: #1949568
> (#1949568) core: allow omitting second part of LoadCredentials= argument

- src/basic/unit-name.c
The path may have unbounded length, for example through a fuse mount.
CVE-2021-33910: attacked controlled alloca() leads to crash in systemd and
ultimately a kernel panic. Systemd parses the content of /proc/self/mountinfo
and each mountpoint is passed to mount_setup_unit(), which calls
unit_name_path_escape() underneath. A local attacker who is able to mount a
filesystem with a very long path can crash systemd and the whole system.
https://bugzilla.redhat.com/show_bug.cgi?id=1970887
The resulting string length is bounded by UNIT_NAME_MAX, which is 256. But we
can't easily check the length after simplification before doing the
simplification, which in turns uses a copy of the string we can write to.
So we can't reject paths that are too long before doing the duplication.
Hence the most …
> (#1984299) basic/unit-name: do not use strdupa() on a path

- src/core/mount.c
- src/core/unit.c
- units/basic.target
- units/tmp.mount
RHEL-only
Resolves: #1959826
(cherry picked from commit 03e52d33bbdea731eaa79545bb1d30c5b21abe3d)
(cherry picked from commit 56bc690688957abe24d434b7ede16cbe0f2d1233)
> (#1959826) unit: don't add Requires for tmp.mount

- units/rc-local.service.in
I think this was the intent of commit 91b684c7300879a8d2006038f7d9185d92c3c3bf,
just network-online.target didn't exist back then.
RHEL-only
Resolves: #1954429
> (#1954429) rc-local: order after network-online.target

- rules.d/40-elevator.rules
- rules.d/meson.build
Kernel removed the elevator= option, so let's reintroduce
it for rhel8 via udev rule.
RHEL-only
Resolves: #1998190
> (#1998190) rules: add elevator= kernel command line parameter

- units/meson.build
Follow-up to #20591.
(cherry picked from commit 220261ef940a126588b20a1765a2501811473839)
Related: #1972223
> (#1972223)  unit: install the systemd-bless-boot.service only if we have gnu-efi

- man/systemd-system.conf.xml
- src/core/main.c
- src/core/system.conf.in
This should be hopefully high enough even for the very big deployments.
Resolves: #1997200
> (#1997200) pid1: bump DefaultTasksMax to 80% of the kernel pid.max value

- man/systemd.link.xml
- test/fuzz/fuzz-link-parser/99-default.link
While stable MAC address for interface types that don't have the
address provided by HW could be useful it also breaks LACP based bonds.
Let's err on the side of caution and don't change the MAC address from
udev.
Resolves: #1921094
> (#1921094) udev/net-setup-link: change the default MACAddressPolicy to "none"

- network/99-default.link
Fix the oversight and change the policy in the link file, i.e. the
place where it actually matters.
Related: #1921094
> (#1921094) udev/net-setup-link: *really* change the default MACAddressPolicy to "none"

- .packit.yml
> (#2017035) ci: use C9S chroots in Packit

- src/test/test-mountpoint-util.c
https://bugzilla.redhat.com/show_bug.cgi?id=1803070
I *think* this a kernel bug: the mnt_id as listed in /proc/self/mountinfo is different
than the one we get from /proc/self/fdinfo/. This only matters when both statx and
name_to_handle_at are unavailable and we hit the fallback path that goes through fdinfo:
(gdb) !uname -r
5.6.19-200.fc31.ppc64le
(gdb) !cat /proc/self/mountinfo
697 664 253:0 /var/lib/mock/fedora-31-ppc64le/root / rw,relatime shared:298 master:1 - xfs /dev/mapper/fedora_rh--power--vm14-root rw,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota
698 697 253:0 /var/cache/mock/fedora-31-ppc64le/yum_cache /var/cache/yum rw,relatime shared:299 master:1 - xfs /dev/mapper/fedora_rh--power--vm14-root rw,seclabel,attr2,inode64,logbufs=8,logbsize=32k,noquota
699 697 253:0 …
> (#2017035) test-mountpointutil-util: do not assert in test_mnt_id()

- src/core/dbus-unit.c
- src/core/load-fragment.c
- src/core/unit-serialize.c
- src/core/unit.c
- src/core/unit.h
- src/test/test-engine.c
Defines a "UNIT_DEPENDENCY_SLICE_PROPERTY" UnitDependencyMask type that
is used when adding slices to the dependencies hashmap. This type is
used to remove slice dependencies when they get overridden by new ones.
Fixes #20182
(cherry picked from commit 899acf5c2d4b89caa891d05ccfa4be828a999c2d)
Resolves: #1989401
> (#1989401) core: replace slice dependencies as they get added

- src/nspawn/nspawn.c
- test/test-functions
We need to do this because idmapped mounts have been disabled in RHEL-9
kernel: https://bugzilla.redhat.com/show_bug.cgi?id=2018141 .
RHEL-only
Fixes #55
Related: #2017035
> Treat EPERM as "not available" too

- test/TEST-56-EXIT-TYPE/test.sh
- test/test-functions
since cgroup empty notifications are unreliable in legacy cgroups.
See: systemd/systemd#22320
Complements: systemd/systemd#22344
(cherry picked from commit e2620820188428de7086f5e8ac41305177f70954)
Related: #2047768
> (#2047768) test: require unified cgroup hierarchy for TEST-56 

- src/shared/tests.h
- src/test/test-barrier.c
- src/test/test-cgroup-setup.c
- src/test/test-chown-rec.c
- src/test/test-format-table.c
- src/test/test-fs-util.c
- src/test/test-hashmap.c
- src/test/test-install-root.c
- src/test/test-load-fragment.c
- src/test/test-mountpoint-util.c
- src/test/test-namespace.c
- src/test/test-proc-cmdline.c
- src/test/test-process-util.c
- src/test/test-sd-hwdb.c
- src/test/test-serialize.c
- src/test/test-sleep.c
- src/test/test-stat-util.c
- src/test/test-time-util.c
- src/test/test-unit-file.c
- src/test/test-unit-name.c
- src/test/test-unit-serialize.c
- src/test/test-utf8.c
I suspect we'd end up backporting this sooner or later anyway, so let's do it now while it's easy...
> (#2017035) tests: rework test macros to not take code as parameters

- man/systemd.link.xml
- network/99-default.link
- test/fuzz/fuzz-link-parser/99-default.link
While stable MAC address for interface types that don't have the
address provided by HW could be useful it also breaks LACP based bonds.
Let's err on the side of caution and don't change the MAC address from
udev.
RHEL-only
Resolves: #2009237
> udev/net-setup-link: change the default MACAddressPolicy to "none"

- src/libsystemd/sd-bus/bus-introspect.c
- src/libsystemd/sd-bus/bus-introspect.h
- src/libsystemd/sd-bus/bus-objects.c
- src/shared/bus-object.c
Otherwise, the generated xml files are not reproducible.
(cherry picked from commit acac88340ace3cd631126eebb6d0390cd54e8231)
Resolves: #2066325
> (#2066325) bus: Use OrderedSet for introspection

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
If we have two or more devices that share the same slot but they are
also multifunction then it is OK to use the slot information even if it
is the same for all of them. Name conflict will be avoided because we
will append function number and form names like, ens1f1, ens1f2...
(cherry picked from commit 66425daf2c68793adf24a48a26d58add8662e83f)
Resolves: #2070097
> (#2070097) udev/net_id: avoid slot based names only for single function devices

- .mergify.yml
Add rules for `needs-ci` label management
RHEL-only
Related: #2087652
---
_This change has been made by @jamacku from https://mergify.com config editor._
> (#2087652) ci(Mergify): Add rules for `needs-ci` label management

- .github/workflows/unit_tests.yml
- src/shared/bus-unit-util.c
- src/shutdown/umount.c
- test/test-functions
Current md_list_get() implementation filters all block devices, started from
"md*". This is ambiguous because list could contain:
- partitions created upon md device (mdXpY)
- external metadata container- specific type of md array.
For partitions there is no issue, because they aren't handle STOP_ARRAY
ioctl sent later. It generates misleading errors only.
Second case is more problematic because containers are not locked in kernel.
They are stopped even if container member array is active. For that reason
reboot or shutdown flow could be blocked because metadata manager cannot be
restarted after switch root on shutdown.
Add filters to remove partitions and containers from md_list. Partitions
can be excluded by DEVTYPE. Containers are determined by MD_LEVEL
property, we are excluding all …
> (#2087677) shutdown: get only active md arrays.

- src/libsystemd/sd-bus/bus-introspect.c
- src/libsystemd/sd-bus/bus-introspect.h
- src/libsystemd/sd-bus/bus-objects.c
- src/shared/bus-object.c
Otherwise, the generated xml files are not reproducible.
(cherry picked from commit acac88340ace3cd631126eebb6d0390cd54e8231)
Resolves: #2068131
> (#2068131) bus: Use OrderedSet for introspection

- man/org.freedesktop.login1.xml
- src/login/logind-session-dbus.c
- src/login/logind-session.c
- src/login/logind-session.h
- src/login/org.freedesktop.login1.conf
Currently, the only way to set display name of a graphical session is to
pass it to CreateSession(). But modern display managers like gdm start
the display server as part of the user session, which means that the
display name isn't known yet when the session is being created. Hence,
let's make it possible to set it later.
(cherry picked from commit 4885d7490b23e08d8444e5a68927ce9ce8727e5a)
Resolves: [#2100340](https://bugzilla.redhat.com/show_bug.cgi?id=2100340)
> (#2100340) logind-session-dbus: allow to set display name via dbus

- .github/workflows/unit_tests.yml
to work around #23987.
(cherry picked from commit d46e7c7cfd6c286a38298c067f16ac784c2a26f0)
Related: #2087652
> (#2087652) ci: limit which env variables we pass through `sudo`

- src/core/load-fragment.c
- src/test/test-load-fragment.c
Fixes a bug introduced by 065364920281e1cf59cab989e17aff21790505c4.
Fixes #22957.
(cherry picked from commit 58dd4999dcc81a0ed92fbd78bce3592c3e3afe9e)
Resolves: [#2073994](https://bugzilla.redhat.com/show_bug.cgi?id=2073994)
> (#2073994) core: command argument can be longer than PATH_MAX

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
If we have two or more devices that share the same slot but they are
also multifunction then it is OK to use the slot information even if it
is the same for all of them. Name conflict will be avoided because we
will append function number and form names like, ens1f1, ens1f2...
(cherry picked from commit 66425daf2c68793adf24a48a26d58add8662e83f)
Resolves: #2073003
> (#2073003) udev/net_id: avoid slot based names only for single function devices

- man/org.freedesktop.systemd1.xml
- man/systemd-system.conf.xml
- src/core/dbus-manager.c
- src/core/device.c
- src/core/main.c
- src/core/manager.c
- src/core/manager.h
- src/core/system.conf.in
Resolves: [#2116681](https://bugzilla.redhat.com/show_bug.cgi?id=2116681)
> (#2116681) Add a configuration option for setting default device timeout

- src/basic/unit-def.c
- src/basic/unit-def.h
- src/core/dbus-scope.c
- src/core/scope.c
- src/core/scope.h
- src/shared/bus-unit-util.c
- test/units/testsuite-19.sh
Previously it was possible to set delegate property for scope, but you
were not able to allow unprivileged process to manage the scope's cgroup
hierarchy. This is useful when launching manager process that  will run
unprivileged but is supposed to manage its own (scope) sub-hierarchy.
Fixes #21683
(cherry picked from commit 03860190fefce8bbea3a6f0e77919b882ade517c)
Resolves: #2120604
> (#2120604) scope: allow unprivileged delegation on scopes

- .github/workflows/differential-shellcheck.yml
It performs differential ShellCheck scans and report results directly in pull request.
documentation: https://github.com/redhat-plumbers-in-action/differential-shellcheck
(inspired by commit https://github.com/systemd/systemd/commit/3f3c718e79abdac698ae90de5cd4c0560a0a75d4)
RHEL-only
Related: #2122500
> (#2122500) ci(lint): add shell linter - Differential ShellCheck

- src/boot/efi/boot.c
- src/boot/efi/cpio.c
- src/boot/efi/secure-boot.c
- src/boot/efi/util.c
- src/boot/efi/util.h
- test/units/testsuite-70.sh
Some distributions have started phasing out SHA1, which breaks the systemd-measure test case in its current form. Let's make sure we can use SHA1 for signing beforehand to mitigate this.
Spotted on RHEL 9, where SHA1 signatures are disallowed by [0]:
```
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "/tmp/pcrsign-private.pem"
...
openssl rsa -pubout -in "/tmp/pcrsign-private.pem" -out "/tmp/pcrsign-public.pem"
writing RSA key
/usr/lib/systemd/systemd-measure sign --current --bank=sha1 --private-key="/tmp/pcrsign-private.pem" --public-key="/tmp/pcrsign-public.pem"
Failed to initialize signature context.
```
[0] https://gitlab.com/redhat/centos-stream/rpms/openssl/-/blob/c9s/0049-Selectively-disallow-SHA1-signatures.patch
(cherry picked from commit …
> (#2141979) test: check if we can use SHA1 MD for signing before using it

- src/core/swap.c
If the page size of a swap space doesn't match the page size of the currently running kernel, swapon will fail. Let's instruct it to reinitialize the swap space instead.
(cherry picked from commit cc137d53e36da5e57b060be5e621864f572b2cac)
Resolves: [#2151993](https://bugzilla.redhat.com/show_bug.cgi?id=2151993)
> (#2151993) swap: tell swapon to reinitialize swap if needed

- man/org.freedesktop.systemd1.xml
- man/systemctl.xml
- shell-completion/bash/systemctl.in
- shell-completion/zsh/_systemctl.in
- src/basic/chase-symlinks.c
- src/basic/glyph-util.c
- src/basic/glyph-util.h
- src/core/dbus-manager.c
- src/rpm/systemd-update-helper.in
- src/shared/install.c
- src/systemctl/systemctl-enable.c
- src/systemctl/systemctl.c
- src/systemctl/systemctl.h
- src/test/test-locale-util.c
- test/test-functions
- test/units/testsuite-64.sh
- test/units/testsuite-65.sh
This reverts & backports the new set of patches for the recent `chase_symlinks*()` without `/proc/` issue.
For RHEL we either want to backport https://github.com/systemd/systemd/pull/25661 as well once it's merged, or drop the warning completely/lower it to debug, hence opening this as a draft for now.
/cc @msekletar
> (#2138081) More `chase_symlinks*()` shenanigans

- src/udev/udev-builtin-net_id.c
Fixes a bug introduced by 78463c6c4fdcb703bc0dc694c3ea77df3c5624e0.
Fixes #25545.
(cherry picked from commit cf74e2e16fb06b7de9e3875c6462290998fb06bd)
Resolves: #2159448
> (#2159448) udev: make get_virtfn_info() provide physical PCI device

- src/shared/elf-util.c
- src/shared/json.c
- src/shared/json.h
- src/test/test-json.c
- test/TEST-64-UDEV-STORAGE/test.sh
- test/units/testsuite-45.sh
Resolves: [#2149074](https://bugzilla.redhat.com/show_bug.cgi?id=2149074)
> (#2149074) Avoid deadlock when passing processed backtrace data

- src/journal/journalctl.c
In journalctl we don't run the static destructors defined via the STATIC_DESTRUCTOR_REGISTER() macro, since it requires a corresponding static_destruct() call. In most cases this is handled by the DEFINE_(TEST_)?MAIN*() macros, but journalctl defines its own main function, so let's handle that as well.
$ valgrind --suppressions=valgrind.supp --show-leak-kinds=all --leak-check=full build/journalctl --no-pager -u system.slice -n 10 >/dev/null ==2778093== Memcheck, a memory error detector
==2778093== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al. ==2778093== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info ==2778093== Command: build/journalctl --no-pager -u system.slice -n 10 ==2778093==
==2778093==
==2778093== HEAP SUMMARY:
==2778093==     in use at exit: …
> (#2122500) journalctl: actually run the static destructors

- src/boot/efi/meson.build
An rpminspect test in Fedora/RHEL is flagging our stub files as having an executable stack. The check is correct:
$ readelf --wide --program-headers build/src/boot/efi/linuxx64.elf.stub | rg -i stack
GNU_STACK      0x000000 0x0000000000000000 0x0000000000000000 0x000000 0x000000 RWE 0x10
It seems to be just an omission in the linker script… None of the objects that are linked into the stub are marked as requiring an executable stack:
$ readelf --wide --sections build/src/boot/efi/*.c.o \
/usr/lib/gnuefi/x64/libgnuefi.a \
/usr/lib/gnuefi/x64/libefi.a \
/usr/lib/gcc/x86_64-redhat-linux/12/libgcc.a \
| rg '.note.GNU-stack.*X'
(nothing)
On aarch64 we end up with a nonexecutable stack, but on ia32 and x64 we get one, so this might be just a matter of defaults in the linker. It doesn't matter …
> (#2140646) efi: drop executable-stack bit from .elf file

- src/shared/install.c
- test/units/testsuite-26.sh
Related: [#2138081](https://bugzilla.redhat.com/show_bug.cgi?id=2138081)
> (#2138081) Fix PID1 crash at `systemctl enable`

- src/login/logind-session.c
(cherry picked from commit 6269ffe7ee8a659df7336a2582054ecd9eecf4b1)
Resolves: [#2172401](https://bugzilla.redhat.com/show_bug.cgi?id=2172401)
> (#2172401) logind-session: make stopping of idle session visible to admins

- src/core/unit.c
Instantly killing delegated scopes is just not viable for our needs in OCP 4.13 in cgroupv1 mode.  We will accept the possibility of timeouts instead.
Co-authored-by: Colin Walters <walters@verbum.org>
rhel-only
Resolves: #2179165
> (#2179165) unit: In cgroupv1, gracefully terminate delegated scopes again

- src/core/unit.c
Instantly killing delegated scopes is just not viable for our needs in OCP 4.13 in cgroupv1 mode.  We will accept the possibility of timeouts instead.
Co-authored-by: Colin Walters <walters@redhat.com>
rhel-only
Resolves: [#2179165](https://bugzilla.redhat.com/show_bug.cgi?id=2179165)
> (#2180120) unit: In cgroupv1, gracefully terminate delegated scopes again

- .github/workflows/differential-shellcheck.yml
Also, update `differential-shellcheck` to the latest version (`v4.0.2`) - https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases Push events are supported since `v4.0.0`.
Fixes: https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
This should get rid of annoying messages from the `github-code-scanning` bot.
> (#2100440) ci: trigger `differential-shellcheck` workflow on push

- docs/ENVIRONMENT.md
- src/basic/compress.c
- src/basic/compress.h
- src/journal/journald-server.c
- src/libsystemd/sd-journal/journal-def.h
- src/libsystemd/sd-journal/journal-file.c
- src/libsystemd/sd-journal/journal-file.h
- test/units/testsuite-04.sh
Resolves: [#2183546](https://bugzilla.redhat.com/show_bug.cgi?id=2183546)
Note: Upstream recently made quite a few changes in [journal-file.c](https://github.com/systemd/systemd/commits/bfeaa62dbc9d2a436e2d3413386ba38f48b5d502/src/libsystemd/sd-journal/journal-file.c)
> (#2183546) sd-journal: allow to specify compression algorithm through env

- .github/workflows/source-git-automation.yml
The new version of `redhat-plumbers-in-action/advanced-commit-linter` requires new permission: `checks: write`.
https://github.com/redhat-plumbers-in-action/advanced-commit-linter/commit/f1bb35fcdeff83d40eb67b5e7c58baad6be689b2
rhel-only
Related: #2170883
---
Check release notes: https://github.com/redhat-plumbers-in-action/advanced-commit-linter/releases/tag/v1.2.0
> (#2170883) ci: update permissions for source-git automation workflows

- .github/advanced-commit-linter.yml
> (#2170883) Allow `RHEL-only` labels to mark downstream-only commits

- src/sulogin-shell/sulogin-shell.c
Resolves: [#2169959](https://bugzilla.redhat.com/show_bug.cgi?id=2169959)
> (#2169959) Fix lost control of the current terminal when default.target is rescue.target

- src/basic/alloc-util.h
- src/basic/macro.h
- src/basic/memory-util.h
- src/libsystemd/sd-journal/journal-vacuum.c
- src/test/meson.build
- src/test/test-macro.c
- src/test/test-memory-util.c
Also includes follow-up cleanups. These are not really needed, but they've given me the opportunity to backport two new macros (`CLEANUP_ARRAY` and `FOREACH_ARRAY`) that we'll likely need sooner or later.
Resolves: [#2182632](https://bugzilla.redhat.com/show_bug.cgi?id=2182632)
> (#2182632) Count size of all journal files when vacuuming

- src/login/systemd-user.in
Setting umask for user sessions via UMASK setting in /etc/login.defs is a well-known feature. Let's make sure that user manager also runs with this umask value.
Follow-up for 5e37d1930b41b24c077ce37c6db0e36c745106c7.
(cherry picked from commit 159f1b78576ce91c3932f4867f07361a530875d3)
Resolves: #2210145
> (#2210145) pam: add call to pam_umask

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
Certain cards support to set their eswitch to switchdev mode. In this mode for each created VF there is also created so called VF representor. This representor is helper network interface used for configuration of mentioned eswitch and belongs to an appropriate PF.
VF representors are identified by the specific value of phys_port_name attribute and the value has format "pfMvfN" where M is PF function number and N is VF number inside this PF.
As the VF representor interfaces belong to PF PCI device the naming scheme used for them is the same like for other PCI devices. In this case name of PF interface is used and phys_port_name suffix is appended.
E.g.
PF=enp65s0f0np0 # phys_port_name for PF interface is 'p0'
VF=enp65s0f0np0v0 # v0 is appended for VF0 in case of NAMING_SR_IOV_V …
> (#2218886) udev-builtin-net_id: align VF representor names with VF names

- src/login/systemd-user.in
A call to pam_namespace is required so that children of user@.service end up in a namespace as expected. pam_namespace gets called as part of the stack that creates a session (login, sshd, gdm, etc.) and those processes end up in a namespace, but it also needs to be called from our stack which is parallel and descends from pid1 itself.
The call to pam_namespace is similar to the call to pam_keyinit that was added in ab79099d1684457d040ee7c28b2012e8c1ea9a4f. The pam stack for user@.service creates a new session which is disconnected from the parent environment. Both calls are not suitable for inclusion in the shared part of the stack (e.g. @system-auth on Fedora/RHEL systems), because for example su/sudo/runuser should not include them.
Fixes #17043 (Allow to execute user service into …
> (#2218184) pam: add a call to pam_namespace

- rules.d/40-redhat.rules
RHEL-only
Fix CPU hotplug regression on s390x introduced by commit 94c7e260b499 ("rules: do not online CPU automatically on IBM platforms")
Resolves: #2212612
> (#2212612) rules: online CPU automatically on IBM s390x platforms

- man/org.freedesktop.systemd1.xml
- src/core/manager.c
- src/test/test-manager.c
In upstream of systemd, cgroups v1 are not considered as supported. This is not true for RHEL, don't taint the host when cgroups v1 are enabled.
rhel-only
Resolves: #2193456
> (#2193456) manager: don't taint the host if cgroups v1 is used

- man/org.freedesktop.systemd1.xml
- src/core/manager.c
- src/test/test-manager.c
In upstream of systemd, cgroups v1 are not considered as supported. This is not true for RHEL, don't taint the host when cgroups v1 are enabled.
rhel-only
Resolves: #2196479
> (#2196479) manager: don't taint the host if cgroups v1 is used

- src/core/service.c
Re-watching pids on cgroup v1 (needed because of unreliability of cgroup empty notifications in containers) is handled bellow at the end of service_sigchld_event() and depends on value main_pid_known flag.
In CentOS Stream 8 container on cgroup v1 the stop action would get stuck indefinitely on unit like this,
$ cat /run/systemd/system/foo.service
[Service]
ExecStart=/bin/bash -c 'trap "nohup sleep 1 & exit 0" TERM;  sleep infinity' ExecStop=/bin/bash -c 'kill -s TERM $MAINPID'
TimeoutSec=0
However, upstream works "fine" because in upstream version of systemd we actually never wait on processes killed in containers and proceed immediately to sending SIGKILL hence re-watching of pids in the cgroup is not necessary. But for the sake of correctness we should merge the patch also upstream. …
> (#2210237) core/service: when resetting PID also reset known flag

- .github/advanced-commit-linter.yml
It's sufficient enough to check only the `systemd/systemd` repo.
Related to https://github.com/redhat-plumbers-in-action/advanced-commit-linter/issues/62
rhel-only
Related: #2170883
> (#2170883) ci: drop systemd-stable from advanced-commit-linter config

- .github/workflows/build_test.sh
- src/core/service.c
This reverts commit ff32060f2ed37b68dc26256b05e2e69013b0ecfe.
This change is incorrect as we don't want to mark the PID as invalid but only mark it as dead.
The change in question also breaks user level socket activation for `podman.service` as the termination of the main `podman system service` process is not properly handled, causing any application accessing the socket to hang.
This is because the user-level `podman.service` unit also hosts two non-main processes: `rootlessport` and `rootlessport-child` which causes the `cgroup_good` check to still succeed.
The original submitter of this commit is recommended to find another more correct way to fix the cgroupsv1 issue on CentOS 8.
(cherry picked from commit 996b00ede87d6a870332e63974a7d4def3c2f1b0)
Resolves: #2225667
Reverts: #2210237
> Revert "core/service: when resetting PID also reset known flag"

- CONTRIBUTING.md
> (#2170883) doc: add downstream CONTRIBUTING document

- CONTRIBUTING.md
based on feedback from: https://github.com/redhat-plumbers/systemd-rhel8/pull/407
rhel-only
Related: #2170883
> (#2170883) doc: improve CONTRIBUTING document

- CONTRIBUTING.md
> (#2170883) doc: use link with prefilled Jira issue

- CONTRIBUTING.md
- README.md
This should increase the visibility of the downstream CONTRIBUTING.
Also, fix some wording and update links.
rhel-only
Related: #2170883
> (#2170883) docs: link downstream CONTRIBUTING in README

- src/core/bpf/restrict_fs/restrict-fs.bpf.c
Linux kernel's bpf-next contains BPF LSM support for s390x. systemd's test-bpf-lsm currently fails with this kernel.
This is an endianness issue: in the restrict_fs bpf program, magic_number has type unsigned long (64 bits on s390x), but magic_map keys are uint32_t (32 bits). Accessing magic_map using 64-bit keys may work by accident on little-endian systems, but fails hard on big-endian ones.
Fix by casting magic_number to uint32_t.
(cherry picked from commit 907046282c27ee2ced5e22abb80ed8df2e157baf)
Resolves: #2230364
> (#2230364) bpf: fix restrict_fs on s390x

- src/shared/netif-naming-scheme.c
rhel-only
Resolves: #2231845
https://github.com/redhat-plumbers/systemd-rhel9/blob/eff259c8c7677bbbe64890873bd64349871dd6c5/man/systemd.net-naming-scheme.xml#L486-L495
https://github.com/redhat-plumbers/systemd-rhel9/blob/eff259c8c7677bbbe64890873bd64349871dd6c5/src/shared/netif-naming-scheme.h#L58
> (#2231845) udev/net_id: use naming scheme for RHEL-9.3

- src/core/timer.c
Resolves: [#2211065](https://bugzilla.redhat.com/show_bug.cgi?id=2211065)
> (#2211065) Always use inactive_exit_timestamp if it is set

- src/core/dbus-manager.c
Fixes a bug introduced by 3b3557c410c7910fae0990599dcb82711cf5fbb7.
Fixes #25625.
(cherry picked from commit 47c57b4813c81187db86ed6e33ecf11f8a25825a)
Resolves: #2226980
> (#2226980) core: use correct scope of looking up units

- src/core/namespace.c
- src/dissect/dissect.c
- src/home/homework-luks.c
- src/nspawn/nspawn.c
- src/portable/portable.c
- src/shared/blockdev-util.c
- src/shared/blockdev-util.h
- src/shared/discover-image.c
- src/shared/dissect-image.c
- src/shared/dissect-image.h
- src/shared/loop-util.c
- src/shared/loop-util.h
- src/sysext/sysext.c
I noticed that `test-loop-block` fails on s390x & ppc64le with:
```
The partition table has been altered.
Syncing disks.
Thu 2023-08-10 10:26:51 EDT (138753) Image name .#sfdisk3c2774149eea9be1 is not valid, ignoring.
Thu 2023-08-10 10:26:51 EDT (138753) Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Thu 2023-08-10 10:26:51 EDT (138753) Found container virtualization none.
Thu 2023-08-10 10:26:51 EDT (138753) Successfully acquired /dev/loop0, devno=7:0, nr=0, diskseq=11
Thu 2023-08-10 10:26:51 EDT (138753) Image name .#sfdisk3c2774149eea9be1 is not valid, ignoring.
Thu 2023-08-10 10:26:51 EDT (138753) Assertion 'dissect_loop_device(loop, NULL, NULL, DISSECT_IMAGE_ADD_PARTITION_DEVICES|DISSECT_IMAGE_PIN_PARTITION_DEVICES, &dissected) >= 0' failed at …
```
> (#2170883) Backport loop-util related stuff to fix `test-loop-block`

- src/nspawn/nspawn.c
- test/units/testsuite-13.sh
Resolves: [#2178222](https://bugzilla.redhat.com/show_bug.cgi?id=2178222)
> (#2178222) Revert workaround for disabled idmapped mounts

- rules.d/40-redhat.rules
RHEL-only
Fix CPU hotplug regression on s390x introduced by commit 94c7e260b499 ("rules: do not online CPU automatically on IBM platforms"). After discussion with IBM, CPUs should be auto-enabled when in the configured state after a hotplug. However, if the CPU is deconfigured, it should not.
This is because on zVM and KVM hotplugged CPUs are configured and on LPAR/DPM they are deconfigured.
Resolves: #2239576
Signed-off-by: Cédric Le Goater <clg@redhat.com>
(cherry picked from commit 65d993c2efe52d683396dc3181cc79f29698bf39)
> (#2239576) rules: online CPU automatically on IBM s390x platforms when configured

- man/systemd-analyze.xml
- shell-completion/bash/systemd-analyze
- shell-completion/zsh/_systemd-analyze
- src/analyze/analyze-plot.c
- src/analyze/analyze.c
- src/analyze/analyze.h
- test/units/testsuite-65.sh
systemd-analyze: Add JSON and table output to systemd-analyze's plot
This cherry-pick adds json and table visualization of `systemd-analyize plot` output. This is needed for CI operations where we need to automate and report on analysis of boot time metrics.
> (RHEL-5070) systemd-analyze: Add JSON and table output to systemd-analyze's plot

- .github/workflows/differential-shellcheck.yml
Exclude all `.in` files because they may contain unsupported syntax, and they have to be preprocessed first. For example:
```sh
Error: SHELLCHECK_WARNING:
./src/rpm/systemd-update-helper.in:130:37: warning[SC1083]: This { is literal. Check expression (missing ;/\n?) or quote it.
```
Related to: https://github.com/systemd/systemd/pull/28521
(cherry picked from commit 97eb82682126e7f3ee956a025078ea2b801955cb)
Related: RHEL-1086
> (RHEL-1086) ci(lint): exclude `.in` files from ShellCheck lint

- src/udev/udevd.c
We might need a lot of fds on large systems, hence raise RLIMIT_NOFILE to what the service manager allows us, which is quite a lot these days.
udev already sets FORK_RLIMIT_NOFILE_SAFE when forking of chilren, thus ensuring that forked off processes get their RLIMIT_NOFILE soft limit reset to 1K for compat with crappy old select().
Replaces: #29298
Fixes: #28583
(cherry picked from commit 1617424ce76d797d081dd6cb1082b954c4d2bf38)
Resolves: RHEL-11040
> (RHEL-11040) udev: raise RLIMIT_NOFILE as high as we can

- src/core/device.c
- src/libsystemd/sd-device/device-private.c
- src/libsystemd/sd-device/device-private.h
- src/libsystemd/sd-device/sd-device.c
- src/libsystemd/sd-netlink/netlink-util.c
- src/libsystemd/sd-netlink/netlink-util.h
- src/libsystemd/sd-netlink/test-netlink.c
- src/udev/net/link-config.c
- src/udev/net/link-config.h
- src/udev/udev-builtin-blkid.c
- src/udev/udev-builtin-btrfs.c
- src/udev/udev-builtin-hwdb.c
- src/udev/udev-builtin-input_id.c
- src/udev/udev-builtin-keyboard.c
- src/udev/udev-builtin-kmod.c
- src/udev/udev-builtin-net_id.c
- src/udev/udev-builtin-net_setup_link.c
- src/udev/udev-builtin-path_id.c
- src/udev/udev-builtin-uaccess.c
- src/udev/udev-builtin-usb_id.c
- src/udev/udev-builtin.c
- src/udev/udev-builtin.h
- src/udev/udev-event.c
- src/udev/udev-event.h
- src/udev/udev-rules.c
- src/udev/udevadm-test-builtin.c
- test/test-network/conf/12-dummy-rename-to-altname.link
- test/test-network/systemd-networkd-tests.py
- test/units/testsuite-17.02.sh
- test/units/testsuite-17.12.sh
> (RHEL-5988) Assign alternative names only on add uevent

- rules.d/40-redhat.rules
Based on #209, it has to be merged first.
> (RHEL-12247) rules: online CPU automatically on IBM s390x platforms when configured

- meson.build
ln_s was added in upstream later on. It's not present in this branch. Fixup for b98da2d9e7.
Related: RHEL-13199
> (RHEL-13199) meson: fix installation of ukify

- src/libsystemd/sd-id128/id128-util.c
- src/libsystemd/sd-id128/id128-util.h
- src/udev/udevadm-trigger.c
- test/units/testsuite-17.02.sh
Addresses https://github.com/redhat-plumbers/systemd-rhel9/pull/191#issuecomment-1849740706 where `udevadm trigger --settle` freezes when used with an about-to-be-renamed device, see https://github.com/systemd/systemd/issues/25115.
> (RHEL-5988) `udevadm trigger --settle` follow-ups

- man/systemctl.xml
The original link pointed to a non-existing page, so let's update it.
> (RHEL-19436) man: mention RHEL documentation in systemctl's man page

- src/resolve/resolved-dns-transaction.c
Fixes https://github.com/systemd/systemd/issues/25676
(cherry picked from commit https://github.com/systemd/systemd/commit/3b4cc1437b51fcc0b08da8cc3f5d1175eed25eb1)
Resolves: RHEL-6216
> (RHEL-6216) resolved: actually check authenticated flag of SOA transaction

- man/systemd.net-naming-scheme.xml
- rules.d/75-net-description.rules
- src/shared/netif-naming-scheme.c
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
Users can currently pick specific versions of NIC naming, but that does not guarantee that NIC names won't change after the kernel adds a new sysfs attribute.
This patch allows for an allow/deny list of sysfs attributes that could be used when composing the name.
These lists can be supplied as an hwdb entry in the form of /etc/udev/hwdb.d/50-net-naming-allowlist.hwdb
net:naming:drvirtio_net
ID_NET_NAME_ALLOW=0
ID_NET_NAME_ALLOW_ACPI_INDEX=1
ID_NET_NAME_ALLOW_ADDR_ASSIGN_TYPE=1
ID_NET_NAME_ALLOW_ADDRESS=1
ID_NET_NAME_ALLOW_ARI_ENABLED=1
ID_NET_NAME_ALLOW_DEV_PORT=1
ID_NET_NAME_ALLOW_FUNCTION_ID=1
ID_NET_NAME_ALLOW_IFLINK=1
ID_NET_NAME_ALLOW_INDEX=1
ID_NET_NAME_ALLOW_LABEL=1
ID_NET_NAME_ALLOW_PHYS_PORT_NAME=1
ID_NET_NAME_ALLOW_TYPE=1
(cherry picked from commit …
> (RHEL-1317) udev: allow/denylist for reading sysfs attributes when composing a NIC name

- man/logind.conf.xml
- src/login/logind-session.c
- src/login/logind.c
> (RHEL-20757) Fixlets for StopIdleSessionSec= logic regarding greeter and background sessions

- .github/tracker-validator.yml
- .github/workflows/source-git-automation-on-demand.yml
- .github/workflows/source-git-automation.yml
* Increase the cron interval to 45 minutes
* Use composite GitHub Action to reduce maintenance cost
* Add Z-streams to an array of supported versions
* Don't fail CI when validation/linting fails; instead show everything in a sticky comment in the PR
> (RHEL-1086) Automation improvements and issue fixes

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.c
- src/shared/netif-naming-scheme.h
rhel-only
Resolves: RHEL-22427
> (RHEL-22427) udev/net_id: introduce naming scheme for RHEL-9.4

- rules.d/50-udev-default.rules.in
- src/basic/errno-util.h
- src/test/test-errno-util.c
- src/udev/meson.build
- src/udev/net/link-config.c
- src/udev/net/link-config.h
- src/udev/udev-builtin-net_driver.c
- src/udev/udev-builtin-net_setup_link.c
- src/udev/udev-builtin.c
- src/udev/udev-builtin.h
Currently the ID_NET_DRIVER is set in net_setup_link builtin. But this is called pretty late in the udev processing chain.
Right now in some custom rules it was workarounded by calling ethtool binary directly, which is ugly.
So let's split this code to a separate builtin.
(cherry picked from commit 2b5b25f123ceb89b3ff45b2380db1c8a88b046d9)
Resolves: RHEL-22443
> (RHEL-22443) udev: add new builtin net_driver

- test/knot-data/knot.conf
knot v3.2 and later does this by default. knot v3.1 still has the default set to
10, but it also introduced a warning that the default will be changed to 0 in
later versions, so it effectively complains about its own default, which then
fails the config check. Let's just set the value explicitly to zero to avoid
that.
```
~# knotc --version
knotc (Knot DNS), version 3.1.6
~# grep nsec3-iterations test/knot-data/knot.conf || echo nope
nope
~# knotc -c /build/test/knot-data/knot.conf conf-check
warning: config, policy[auto_rollover_nsec3].nsec3-iterations defaults to 10, since version 3.2 the default becomes 0
Configuration is valid
```
Follow-up to 0652cf8e7b.
(cherry picked from commit cb3244c0dcea80ad35e5bcaf7a07bd449ac65325)
Related: RHEL-1086
> (RHEL-1086) test: explicitly set nsec3-iterations to 0 

- man/systemd.net-naming-scheme.xml
follow-up to: dcc59dffa5116bf96618065cd60742cb660224b8
rhel-only
Related: RHEL-7026
> (RHEL-7026) doc: add missing `<listitem>` to `systemd.net-naming-scheme.xml`

- units/systemd-boot-system-token.service
/lib/systemd/system/systemd-boot-system-token.service:20: Unknown key name 'ConditionPathExists|' in section 'Unit', ignoring
Follow-up for 0a1d8ac77a21ae0741bdf4af08f3a71354805ff1
(cherry picked from commit 0f6d54ca47662f1386ada65ed179a1afd6e727e4)
Related: RHEL-16952
> (RHEL-16952) units: fix typo in Condition in systemd-boot-system-token

- src/resolve/resolved-dns-dnssec.c
- src/resolve/resolved-dns-dnssec.h
- src/resolve/resolved-dns-transaction.c
> (RHEL-26643) resolved: limit the number of signature validations in a transaction

- src/boot/efi/meson.build
https://learn.microsoft.com/en-us/windows/win32/debug/pe-format?redirectedfrom=MSDN#optional-header-windows-specific-fields-image-only
Resolves: RHEL-26133
RHEL-only
[msekleta: this is RHEL-only because upstream no longer uses objcopy to create PE files]
> (RHEL-26133) efi: alignment of the PE file has to be at least 512 bytes

- units/systemd-pcrfs-root.service.in
- units/systemd-pcrfs@.service.in
- units/systemd-pcrmachine.service.in
- units/systemd-pcrphase-initrd.service.in
- units/systemd-pcrphase-sysinit.service.in
- units/systemd-pcrphase.service.in
These units are also present in the initrd, so instead of an assert, just use a condition so they are skipped where they need to be skipped.
Fixes https://github.com/systemd/systemd/issues/26358
(cherry picked from commit 7ef09e2099a4f97ad40748d6b7c735b45aa4c990)
Related: RHEL-16182
---
Noticed this while testing #238. This doesn't affect RHEL 9 directly (yet), since RHEL 9's dracut doesn't pull in these files, but once that change gets backported we'd start seeing fails in journal. Since we're going to do another RHEL 9 build anyway, let's throw this one in as well.
> (RHEL-16182) units: change assert to condition to skip running in initrd/os

- .packit.yml
- src/udev/udevd.c
- test/knot-data/knot.conf
- test/units/testsuite-07.main-PID-change.sh
We might need a lot of fds on large systems, hence raise RLIMIT_NOFILE to what the service manager allows us, which is quite a lot these days.
udev already sets FORK_RLIMIT_NOFILE_SAFE when forking of chilren, thus ensuring that forked off processes get their RLIMIT_NOFILE soft limit reset to 1K for compat with crappy old select().
Replaces: #29298
Fixes: #28583
(cherry picked from commit 1617424ce76d797d081dd6cb1082b954c4d2bf38)
Resolves: RHEL-27383
> (RHEL-27383) udev: raise RLIMIT_NOFILE as high as we can

- src/core/execute.c
Let's enforce that callers pass AT_FDCWD as read_dfd to load_credential() to avoid an assert() in read_full_file_full() if read_dfd is -1.
(cherry picked from commit 661e4251a5b157d1aee1df98fbd2f0c95285ebba)
Resolves: RHEL-31783
> (RHEL-31783) execute: Pass AT_FDCWD instead of -1

- src/core/execute.c
Let's enforce that callers pass AT_FDCWD as read_dfd to load_credential() to avoid an assert() in read_full_file_full() if read_dfd is -1.
(cherry picked from commit 661e4251a5b157d1aee1df98fbd2f0c95285ebba)
Resolves: RHEL-32259
> (RHEL-32259) execute: Pass AT_FDCWD instead of -1

- src/ukify/test/test_ukify.py
Which dropped some whitespaces in the output:
```
$ openssl version
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)
$ openssl x509 -in cert.pem -text -noout | grep Issuer
Issuer: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
$ openssl version
OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023)
$ openssl x509 -in cert.pem -text -noout | grep Issuer
Issuer: C = XX, L = Default City, O = Default Company Ltd
Making test-ukify unhappy:
>       assert 'Issuer: CN = SecureBoot signing key on host' in out
E       AssertionError: assert 'Issuer: CN = SecureBoot signing key on host' in '<...snip...>Issuer: CN=SecureBoot signing key on host archlinux2\n...'
```
(cherry picked from commit 338ed5bea4fcd0b5b1cdcfb96a789edf6251bbdd)
Related: RHEL-30372
> (RHEL-30372) ukify: make the test happy with the latest OpenSSL 

- src/analyze/analyze-inspect-elf.c
- src/basic/macro.h
- src/basic/socket-util.c
- src/basic/socket-util.h
- src/coredump/coredump.c
- src/shared/coredump-util.c
- src/shared/coredump-util.h
- src/shared/elf-util.c
- src/shared/elf-util.h
- src/test/test-coredump-util.c
- test/test-functions
- test/units/testsuite-74.coredump.sh
Note that entering container namespace has to be explicitly enabled by setting SYSTEMD_COREDUMP_ALLOW_NAMESPACE_CHANGE environment variable.
RHEL-only
Resolves: RHEL-29430
> (RHEL-29430) coredump: generate stacktraces also for processes running in containers w/o coredump forwarding

- src/analyze/analyze-inspect-elf.c
- src/basic/macro.h
- src/basic/socket-util.c
- src/basic/socket-util.h
- src/coredump/coredump.c
- src/shared/coredump-util.c
- src/shared/coredump-util.h
- src/shared/elf-util.c
- src/shared/elf-util.h
- src/test/test-coredump-util.c
- src/ukify/test/test_ukify.py
- test/test-functions
- test/units/testsuite-74.coredump.sh
Note that entering container namespace has to be explicitly enabled by setting SYSTEMD_COREDUMP_ALLOW_NAMESPACE_CHANGE environment variable.
RHEL-only
Resolves: RHEL-34061
> (RHEL-34061) coredump: generate stacktraces also for processes running in containers w/o coredump forwarding

- src/analyze/analyze-inspect-elf.c
- src/basic/macro.h
- src/basic/socket-util.c
- src/basic/socket-util.h
- src/coredump/coredump.c
- src/shared/coredump-util.c
- src/shared/coredump-util.h
- src/shared/elf-util.c
- src/shared/elf-util.h
- src/test/test-coredump-util.c
- test/test-functions
- test/units/testsuite-74.coredump.sh
Note that entering container namespace has to be explicitly enabled by setting SYSTEMD_COREDUMP_ALLOW_NAMESPACE_CHANGE environment variable.
RHEL-only
Resolves: RHEL-34059
> (RHEL-34059) coredump: generate stacktraces also for processes running in containers w/o coredump forwarding

- src/journal-remote/microhttpd-util.h
- src/resolve/resolved-dns-server.h
- src/shared/install.h
- test/units/testsuite-17.03.sh
> (RHEL-30372) Fix TEST-17-UDEV under ASan (and a couple of gcc warnings)

- src/shared/bootspec.c
- test/fuzz/fuzz-bootspec/clusterfuzz-testcase-minimized-fuzz-bootspec-5731869371269120
Fixes [oss-fuzz#53578](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53578).
(cherry picked from commit 46dc071985ff487f5ccf20808531168a6add73d3)
Resolves: RHEL-36284
> (RHEL-36284) bootspec: fix null-dereference-read

- src/kernel-install/90-uki-copy.install
For "kernel-install remove ..." only the kernel version is passed, not the kernel image.  So auto-detecting KERNEL_INSTALL_IMAGE_TYPE and setting KERNEL_INSTALL_LAYOUT does not work for uninstall.
The 90-uki-copy.install plugin must consider this and *not* exit early for the "remove" command, otherwise $BOOT_ROOT will be filled with stale kernel images.
Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
(cherry picked from commit 3037616d8ed68f3263746e3c6399d4a05242068b)
Resolves: RHEL-36505
> (RHEL-36505) kernel-install: fix uki-copy deinstall

- .packit.yml
Once default branch is changed to `c10s` the current configuration could stop working.
rhel-only
Related: RHEL-30372
> (RHEL-30372) ci(packit): explicitly clone `c9s` branch

- src/kernel-install/90-uki-copy.install
For "kernel-install remove ..." only the kernel version is passed, not the kernel image.  So auto-detecting KERNEL_INSTALL_IMAGE_TYPE and setting KERNEL_INSTALL_LAYOUT does not work for uninstall.
The 90-uki-copy.install plugin must consider this and *not* exit early for the "remove" command, otherwise $BOOT_ROOT will be filled with stale kernel images.
Signed-off-by: Gerd Hoffmann <kraxel@redhat.com>
(cherry picked from commit 3037616d8ed68f3263746e3c6399d4a05242068b)
Resolves: RHEL-35994
> (RHEL-35994) kernel-install: fix uki-copy deinstall

- .github/tracker-validator.yml
> (RHEL-30372) ci(src-git): add RHEL-9.1 and RHEL-9.1.z to allowed versions

- meson.build
We want to avoid reinitialization of our global variables with static storage duration in case we get dlopened multiple times by the same application. This will avoid potential resource leaks that could have happened otherwise (e.g. leaking journal socket fd).
Resolves: RHEL-6589
> (RHEL-6589) libsystemd: link with '-z nodelete'

- src/basic/string-util.c
- src/basic/utf8.c
- src/test/meson.build
- src/test/test-ellipsize.c
- src/test/test-gunicode.c
> (RHEL-31219) Prevents underlined lines displayed after executing 'systemctl status'

- src/core/mount.c
Fixes #31337
(cherry picked from commit 8e94bb62a5c1309c56c57e0a505aae13a2ac5f4f)
Resolves: RHEL-13159
> (RHEL-13159) core/mount: if umount(8) fails but mount disappeared, assume success

- src/pstore/pstore.c
A change in the kernel[1] renamed the prefix of the pstore files from `dmesg-efi-` to `dmesg-efi_pstore-`.
[1]
https://git.kernel.org/linus/893c5f1de620
(cherry picked from commit ef87c84e812cbdca4ef160fb0536d1f1bc6a2400)
Resolves: RHEL-20322
> (RHEL-20322) fix: prefix of dmesg pstore files

- src/cryptsetup/cryptsetup-tokens/luks2-tpm2.c
- src/cryptsetup/cryptsetup-tpm2.c
- src/shared/bootspec.c
- src/shared/tpm2-util.c
- test/fuzz/fuzz-bootspec/clusterfuzz-testcase-minimized-fuzz-bootspec-5731869371269120
Salt was added in v253. We are not checking whether it was actually found (non-zero size), so when an old tpm+pin enrollment is opened things go boom. For good measure, check both the buffer and the size in both places.
Assertion 'saltlen > 0' failed at src/shared/tpm2-util.c:2490, function tpm2_util_pbkdf2_hmac_sha256(). Aborting.
(cherry picked from commit 504d0acf61c8472bc93c2a927e858074873b2eaf)
Resolves: RHEL-40119
> (RHEL-40119) cryptsetup: do not assert when unsealing token without salt

- src/test/test-mountpoint-util.c
Even /dev isn't always guaranteed to be a mount point, so let's drop this part of the test.
(cherry picked from commit bacad14f94a4e98c3e81d821c56dbe7e2e4726ff)
Related: RHEL-30372
> (RHEL-30372) Drop /dev test in test-mountpoint-util

- test/fuzz/meson.build
- tools/meson-build.sh
- tools/oss-fuzz.sh
Prompted by #29972, because right now it's practically impossible to pass
-fno-sanitize=function to the fuzzer targets without some extensive
sed'ing.
This splits both c_args and cpp_args to separate arguments for
tools/meson-build.sh, because the other way would be to use `eval`, so
the space-separated but quoted strings passed to these options are not
split where they shouldn't, and I'd rather avoid using `eval` if
possible.
Also, this switches the positional arguments we pass to `meson setup`,
as they were in incorrect order (docs say it should be buildir followed
by sourcedir); meson is apparently clever enough to figure this out and
switch the arguments around if necessary, so it didn't complain.
(cherry picked from commit https://github.com/redhat-plumbers/systemd-rhel9/commit/17ee59 …
> (RHEL-30372) fuzz: pass -Dc_args=/-Dcpp_args= to fuzzer targets

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
This effectively reverts 66425daf2c68793adf24a48a26d58add8662e83f.
The commit assumes that if the network interface has multifunctions, then the function fields of the pci devices under the same PCI bridge device are unique.
But it seems not, at least on some setups. See issue #28929. Let's revert the change, and always refuse to set slot base naming if a PCI bridge is detected.
Fixes #28929.
(cherry picked from commit af7417ac7b07bc01232982bf46e9d72e69e7f820)
Resolves: RHEL-44630
> (RHEL-44630) netif-naming-scheme: disable NAMING_BRIDGE_MULTIFUNCTION_SLOT

- src/shared/netif-naming-scheme.c
In 753e1b1c9b255d528eb8b2a2af072a83eb85d784 we forgot to update the netif-naming-scheme.c file to allow people to actually use the new rhel-9.5 scheme.
RHEL-only
Resolves: RHEL-44630
> (RHEL-44630) netif-naming-scheme: make actually possible to use rhel-9.5 scheme

- src/shared/generator.c
- src/shared/generator.h
Inlining of these functions changed ABI of libsystemd-shared which causes issue on update when generators packaged in systemd-udev subpackage fail to execute because of ABI change. systemd and the library are already updated while systemd-udev subpackage is not and hence old generators can't be started when systemd is reexecuting due to internal library incompatibility.
rhel-only: bugfix
Resolves: RHEL-33436
> (RHEL-33436) generator: "uninline" generator_open_unit_file and generator_add_symlink

- src/shared/generator.c
- src/shared/generator.h
Inlining of these functions changed ABI of libsystemd-shared which causes issue on update when generators packaged in systemd-udev subpackage fail to execute because of ABI change. systemd and the library are already updated while systemd-udev subpackage is not and hence old generators can't be started when systemd is reexecuting due to internal library incompatibility.
rhel-only: bugfix
Resolves: RHEL-49495
> (RHEL-49495) generator: "uninline" generator_open_unit_file and generator_add_symlink

- src/cryptsetup/cryptsetup-tokens/cryptsetup-token-systemd-fido2.c
- src/cryptsetup/cryptsetup-tokens/cryptsetup-token-systemd-pkcs11.c
- src/cryptsetup/cryptsetup-tokens/cryptsetup-token-systemd-tpm2.c
- src/shared/libfido2-util.c
- src/shared/libfido2-util.h
> (RHEL-36276) Two followups that make unlocking with PIN locked yubikey actually work

- src/kernel-install/kernel-install.in
> (RHEL-50672) Harden /bin/kernel-install to avoid failing silently when /etc/machine-id doesn't end with newline

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
> (RHEL-50103) Backport NAMING_FIRMWARE_NODE_SUN

- man/systemd.net-naming-scheme.xml
- src/shared/netif-naming-scheme.h
- src/udev/udev-builtin-net_id.c
This reverts commit 7af151ca282d506a8e409a68b656f6d1cd2f13fb.
It seems that virtio devices always have "0" in
the firmware_node/sun. And because of that, udev will always name the device ens0, which leads to collisions. So let's disable it for now.
rhel-only: policy
Reverts: RHEL-50103
> (RHEL-50103) Revert "udev-builtin-net_id: use firmware_node/sun for ID_NET_NAME_SLOT"

- src/ukify/test/test_ukify.py
(cherry picked from commit 5121f7c45b37afca53c89f42123b1dd6a04fa80f)
Related: RHEL-56019
> (RHEL-56019) ukify: Skip test on architectures without UEFI

- man/systemd.special.xml
We had several users, that wrote their unit files with WantedBy=default.target because it should be started "every time". But for example in Fedora/CentOS/RHEL, this often breaks for example selinux relabels (where we just want to do a relabel and reboot).
(cherry picked from commit 67b6404b80cf8078f3d9ec6d4c2f34ac25b15077)
Resolves: RHEL-36531
> (RHEL-36531) man: using WantedBy=default.target is not a good idea

- src/login/logind-session.c
- src/login/logind-session.h
We only want to do this for fully set up, interactive sessions, i.e. user and user-early, but not for any others, hence restrict the rules a bit.
Follow-up for: 508b4786e8592e82eb4832549f74aaa54335d14c
(cherry picked from commit ad23439eae718ac3634f260be0d29e01445983a8)
Related: RHEL-24340
> (RHEL-24340) logind: tighten for which classes of sessions we do stop-on-idle

- src/basic/uid-alloc-range.c
This effectively reverts a change in 115d5145a257c1a27330acf9f063b5f4d910ca4d 'journald: move uid_for_system_journal() to uid-alloc-range.h', which slipped in an additional check of uid_is_container(uid). The problem is that that change is not backwards-compatible at all and very hard for users to handle. There is no common agreement on mappings of high-range uids. Systemd declares ownership of a large range for container uids in https://systemd.io/UIDS-GIDS/, but this is only a recent change and various sites allocated those ranges in a different way, in particular FreeIPA uses (used?) uids from this range for human users. On big sites with lots of users changing uids is obviously a hard problem. We generally assume that uids cannot be "freed" and/or changed and/or reused safely, so we …
> (RHEL-70103) journal: again create user journals for users with high uids

- src/shared/install.c
- test/test-systemctl-enable.sh
For unit instances install_info_discover() returns path to the template, which then generates confusing errors when passed to do_unit_file_enable():
~# build/systemctl --root=/tmp/systemctl-test.N9ysbz reenable templ1@two.service Unit name: templ1@two.service; p: /etc/systemd/system/templ1@.service Removed "/tmp/systemctl-test.N9ysbz/etc/systemd/system/services.target.wants/templ1@two.service". Failed to reenable templ1@.service, destination unit services.target is a non-template unit.
This can also be seen with a different reproducer using getty@.service and a simple bind mount to / - there's no error this time, but it tries to create a symlink for the default instance (from DefaultInstance=tty1), which is also incorrect:
~# SYSTEMD_LOG_LEVEL=debug systemctl --root /mnt/bindroot/ …
> (RHEL-5956) install: don't translate unit instances to paths when reenabling them

- rules.d/50-udev-default.rules.in
PTP device symlink creation rules are currently executed only when the udev action is 'add'. If a user reloads the rules and runs the udevadm trigger command to reapply changes, the symlink may be deleted, which can prevent the chronyd service from restarting properly.
Signed-off-by: Chengen Du <chengen.du@canonical.com>
(cherry picked from commit 6bd12be3fa7761f190e17efdbdbff4440da7528b)
Resolves: RHEL-59088
> (RHEL-59088) udev: Handle PTP device symlink properly on udev action 'change'

- src/systemctl/systemctl.c
> (RHEL-3906) systemctl: print warning about missing /proc only as debug message

- .github/workflows/deploy-man-pages.yml
rhel-only: ci
Related: RHEL-70884
> (RHEL-70884) ci: use ubuntu 22:04 for deploy of man pages

- test/TEST-64-UDEV-STORAGE/test.sh
This feature has been deprecated since QEMU 5.0 and finally removed in QEMU 9.1 [0] which now causes issues when running the storage tests on latest Arch:
```
------ testcase_long_sysfs_path: BEGIN ------
...
qemu-system-x86_64: -device virtio-blk-pci,drive=drive0,scsi=off,bus=pci_bridge25: Property 'virtio-blk-pci.scsi' not found E: qemu failed with exit code 1
```
[0] https://github.com/qemu/qemu/commit/a271b8d7b2f39275a05e49deb7c8edc20b7a8279
(cherry picked from commit cd57920fbf6a8f7769a82cfc9bebc12965de0199)
Related: RHEL-70884
> (RHEL-70884) test: drop removed SCSI passthrough feature

- src/core/core-varlink.c
- src/fuzz/fuzz-bootspec.c
- src/home/homed-varlink.c
- src/machine/machined-varlink.c
- src/nspawn/nspawn-oci.c
- src/nss-resolve/nss-resolve.c
- src/oom/oomd-manager.c
- src/resolve/resolvectl.c
- src/resolve/resolved-varlink.c
- src/shared/group-record.c
- src/shared/json.c
- src/shared/json.h
- src/shared/user-record.c
- src/shared/userdb.c
- src/shared/varlink.c
- src/shared/varlink.h
- src/test/test-varlink.c
- src/userdb/userwork.c
> (RHEL-55266) Return ESRCH if userdb service refuses a user/group name as invalid

- src/core/cgroup.c
- src/core/dbus-job.c
- src/core/dbus-unit.c
- src/core/job.c
- src/core/scope.c
- src/core/service.c
- src/core/unit.c
- src/test/test-execute.c
- test/units/testsuite-17.02.sh
- test/units/testsuite-17.07.sh
- test/units/testsuite-17.08.sh
- test/units/testsuite-17.09.sh
- test/units/testsuite-17.12.sh
- test/units/testsuite-19.cleanup-slice.sh
- test/units/testsuite-26.sh
- test/units/testsuite-35.sh
- test/units/testsuite-45.sh
- test/units/testsuite-58.sh
- test/units/testsuite-60.sh
- test/units/testsuite-65.sh
- test/units/testsuite-71.sh
- test/units/testsuite-73.sh
- test/units/testsuite-75.sh
- test/units/testsuite-76.sh
- test/units/util.sh
> (RHEL-55301) Don't GC unit if it is in another queue

- src/core/unit.c
This ensures that cg_kill_items returns the correct value to let the manager know that a process was killed.
(cherry picked from commit 500cd2e83b8246fbf20d99db898039cfba746223)
Resolves: RHEL-86239
> (RHEL-86239) unit: always return 1 in log_kill

- src/core/unit.c
This ensures that cg_kill_items returns the correct value to let the manager know that a process was killed.
(cherry picked from commit 500cd2e83b8246fbf20d99db898039cfba746223)
Resolves: RHEL-78170
> (RHEL-78170) unit: always return 1 in log_kill

- .github/workflows/gather-metadata.yml
- .packit.yml
- src/login/logind-session.c
- src/login/logind-session.h
We only want to do this for fully set up, interactive sessions, i.e. user and user-early, but not for any others, hence restrict the rules a bit.
Follow-up for: 508b4786e8592e82eb4832549f74aaa54335d14c
(cherry picked from commit ad23439eae718ac3634f260be0d29e01445983a8)
Resolves: RHEL-68299
> (RHEL-68299) logind: tighten for which classes of sessions we do stop-on-idle

- src/backlight/backlight.c
Some AMD systems have support for features like custom brightness curve or adaptive backlight management.  These features allow the display driver to adjust the brightness based upon other factors than just the user brightness request.
The user's brightness request is indicated in the 'brightness' file but the effective result of the logic in the display driver is stored in the 'actual_brightness' file.
This leads to problems when shutting the system down because the value of 'actual_brightness' may be lower than 'brightness' and the wrong value gets stored for the next boot.
For example if the brightness a user requested was 150, the actual_brightness might be 130. So the next boot the brightness will be "set" to 130, but the actual brightness might be 115. If the user reboots again it …
> (RHEL-86714) backlight: Drop support for actual_brightness

- .github/workflows/gather-metadata.yml
- .packit.yml
- src/core/slice.c
- test/units/testsuite-65.sh
Before this fix, when recursive-errors was set to 'no' during a systemd-analyze verification, the parent slice was checked regardless. The 'no' setting means that, only the specified unit should be looked at and verified and errors in the slices should be ignored. This commit fixes that issue.
Example:
Say we have a sample.service file:
[Unit]
Description=Sample Service
[Service]
ExecStart=/bin/echo "a"
Slice=support.slice
Before Change:
systemd-analyze verify --recursive-errors=no maanya/sample.service Assertion 'u' failed at src/core/unit.c:153, function unit_has_name(). Aborting. Aborted (core dumped)
After Change:
systemd-analyze verify --recursive-errors=no maanya/sample.service {No errors}
(cherry picked from commit f660c7fa56b247c278fdb2ebcfea37912f249524)
Related: RHEL-29761
> (RHEL-29761) fix: do not check/verify slice units if recursive errors are to be ignored

- test/units/testsuite-64.sh
New version of mdadm now asks a second question, so send 'y' twice to it in the test scripts
[    5.253483] TEST-64-UDEV-STORAGE.sh[684]: + echo y
[    5.254412] TEST-64-UDEV-STORAGE.sh[685]: + mdadm --create /dev/md/mdmirror --name mdmirror --uuid aaaaaaaa:bbbbbbbb:cccccccc:00000001 /dev/disk/by-id/scsi-0systemd_foobar_deadbeefmdadm0 /dev/disk/by-id/scsi-0systemd_foobar_deadbeefmdadm1 -v -f --level=1 --raid-devices=2
[    5.254759] TEST-64-UDEV-STORAGE.sh[685]: To optimalize recovery speed, it is recommended to enable write-indent bitmap, do you want to enable it now? [y/N]? mdadm: Note: this array has metadata at the start and
[    5.255085] TEST-64-UDEV-STORAGE.sh[685]:     may not be suitable as a boot device.  If you plan to
[    5.255418] TEST-64-UDEV-STORAGE.sh[685]:     store …
> (RHEL-79977) test: answer 2nd mdadm --create question for compat with new version

- src/shared/fileio-label.c
- src/user-sessions/user-sessions.c
pam_nologin looks for /etc/nologin and /run/nologin. user-sessions creates (and removes) /run/nologin, but also removes /etc/nologin. (This behaviour is unchanged since the introduction of the binary in e92787416c691c3f34f47349e5eae3fa68eae856.)
By not removing pam_nologin we fully drop compatibility with PAM < 1.1. This has the advantage that now /etc/nologin can be used by administrator to disable user logins, e.g. for extended maintanance. We already specified PAM >= 1.1.2 as dependency, so this was already covered.
The makes the code match the man page.
Fixes #26965.
(cherry picked from commit a78413baae0e999384b535d327203ebf417b1e24)
Resolves: RHEL-85467
> (RHEL-85467) user-sessions: do not remove /etc/nologin

- src/core/cgroup.c
- src/core/cgroup.h
- src/core/scope.c
- test/TEST-55-OOMD/test.sh
- test/units/testsuite-55.sh
If we add a drop-in for init.scope (e.g.: to set some memory limit), it will be loaded long after the cgroup has already been realized. Do it again when creating the special unit.
(cherry picked from commit 020b2e41ea776cff73392da8084a0725b590d245)
Resolves: RHEL-103488
> (RHEL-103488) core: ensure init.scope is realized after drop-ins have been loaded

- src/boot/efi/util.h
We were using the wrong memory type when allocating pool memory. This does not seem to cause a problem on x86, but the kernel will fail to boot at least on ARM in QEMU.
This is caused by mixing different allocation types which ended up breaking the kernel or EDK2 during boot services exit. Commit 2f3c3b0bee5534f2338439f04b0aa517479f8b76 appears to fix this boot failure because it was replacing the gnu-efi xpool_print with xasprintf thereby unifying the allocation type.
But this same issue can also happen without this fix somehow when the random-seed logic is in use.
Fixes: #27371
(cherry picked from commit ec232e4abd7aebfec06b4814b30129532b2bcefd)
Resolves: RHEL-108555
> (RHEL-108555) boot: Use correct memory type for allocations

- network/meson.build
(cherry picked from commit 6256c65aad2a719ac9054961561bb26e497208ce)
Resolves: RHEL-111611
> (RHEL-111611) meson: /etc/systemd/network is also used by udevd

- network/meson.build
(cherry picked from commit 6256c65aad2a719ac9054961561bb26e497208ce)
Resolves: RHEL-109096
> (RHEL-109096) meson: /etc/systemd/network is also used by udevd

- src/core/dbus-mount.c
- src/core/mount.c
- src/core/mount.h
- src/libsystemd/sd-bus/bus-message.c
- test/units/testsuite-07.mount-invalid-chars.sh
> (RHEL-108584) Backport follow-ups for - core/mount: escape invalid UTF8 char in dbus reply

- src/journal/journald-stream.c
Closes #35390.
(cherry picked from commit c576ba7182f54f352c03f0768c9178b173fb8bcb)
Resolves: RHEL-111065
> (RHEL-111065) journald: extend STDOUT_STREAMS_MAX to 64k

- src/fundamental/memory-util-fundamental.h
Our HAVE_* variables are defined to 0 or 1, so '#if defined(HAVE_*)' is always true. The variable is not defined when compiling for EFI though, so we need the additional guard.
Fixup for 3f92dc2fd4070b213e6bc85263a9bef06ec9a486.
(I don't want to do something like add -DHAVE_EXPLICIT_BZERO=0 to the commandline in src/efi/boot/meson.build, because this quite verbose. Our compilation commandlines are very long already. Let's instead keep this localized in this one spot in the source file.)x
(cherry picked from commit 5deb391c6e6d2b8fd7b94234efea49cd6bee0d76)
Resolves: RHEL-108568
> (RHEL-108568) fundamental: fix compile check for explicit_bzero

- .packit.yml
- src/journal/journald-server.c
> (RHEL-117274) Do not rotate unrelated journal files when full or corrupted

- src/test/test-fd-util.c
On s390x this test fails when the SUT uses the z90crypt kernel module, as it's an another FD the test doesn't account for:
```
/* test_rearrange_stdio */
Successfully forked off 'rearrange' as PID 57293.
test_rearrange_stdio: r=0
/proc/57293/fd:
total 0
lrwx------. 1 root root 64 Apr  5 06:18 0 -> /dev/pts/0 lrwx------. 1 root root 64 Apr  5 06:18 1 -> /dev/pts/0 lrwx------. 1 root root 64 Apr  5 06:18 2 -> /dev/pts/0 lrwx------. 1 root root 64 Apr  5 06:18 3 -> /dev/z90crypt rearrange terminated by signal ABRT.
```
Debugging this was pain, since the child process didn't log anything once we closed stdout/stderr (for obvious reasons). Let's fix both issues by switching logging to kmsg once we close stdin/stdout/stderr, and also by making the test work fine when there are some extra FDs in …
> (RHEL-114974) test: make test-fd-util more lenient when using fd_move_above_stdio()

- src/basic/filesystems-gperf.gperf
- src/basic/missing_magic.h
Kernel commit cb12fd8e0dabb9a1c8aef55a6a41e2c255fcdf4b added pidfs. Update filesystems-gperf.gperf and missing_magic.h accordingly.
This fixes the following error building against a bleeding edge kernel.
```
../src/basic/meson.build:234:8: ERROR: Problem encountered: Unknown filesystems defined in kernel headers:
Filesystem found in kernel header but not in filesystems-gperf.gperf: PID_FS_MAGIC
```
(cherry picked from commit ed01b92e1c92871bbd92711f280e2b2d15753f0e)
Resolves: RHEL-114974
> (RHEL-114974) basic: add PIDFS magic (#31709)
